### ISSUE TITLE
output not a regular hash digest

### ISSUE THREAD

**Issue by Francisobiagwu** [lukechampine/lthash#2]
Hello Luke,
I modified the code a bit to enable me print out the values of the hash. I was surprised that the values are in form of list instead of the regular h ash digests. 

package main
import "lukechampine.com/lthash"
import (
	"fmt"
	"reflect"
)

func createNewLtInstance() lthash.Hash {
	h := lthash.New16()
	fmt.Println(reflect.TypeOf(h))
	return h
}

func incrementHash(h lthash.Hash, m string) []byte {
	h.Add([]byte(m))
	newSum := h.Sum(nil)
	fmt.Println(newSum)
	return newSum

}

func decrementHash(h lthash.Hash, m string) []byte {
	h.Remove([]byte(m))
	newSum := h.Sum(nil)
	fmt.Println(newSum)
	return newSum
}

func main() {
	a := createNewLtInstance()
	incrementHash(a, "apple")
	incrementHash(a, "mango")
	incrementHash(a, "tomatoes")
	decrementHash(a, "apple")
	incrementHash(a, "avocado")
	//fmt.Println(a)

}

**Comment by lukechampine** [comment]
In Go, []byte is printed as a list of integers by default. You can print it as a hex digest using printf or the hex package: 

```go
fmt.Printf("%x\n", sum)
fmt.Println(hex.EncodeToString(sum))
```

**Comment by Francisobiagwu** [comment]
Thanks for your response. I noticed that the h.remove() function doesn't check if the value exists prior. For example, using your original sample code, I removed 'Evil_banana' instead of 'Banana' and I got a hash. I was expecting some form of exception.

h := lthash.New16()
// compute the combined hash of "Apple", "Banana", and "Orange"
h.Add([]byte("Apple"))
h.Add([]byte("Banana"))
h.Add([]byte("Orange"))
oldSum := h.Sum(nil)

// replace "Banana" with "Grape"; the resulting hash is the same
// as the combined hash of "Apple", "Grape", and "Orange".
h.Remove([]byte("Evil_Banana"))
h.Add([]byte("Grape"))
newSum := h.Sum(nil)

**Comment by lukechampine** [comment]
An LtHash is not really a set of items; it's more like a mathematical sum. You can add or remove any item from the hash and get a certain value, but that value is only meaningful under specific circumstances.

Here's an analogy. Imagine that I have a set of numbers: 2, 3 and 5. I can add these numbers together to produce their sum, 10. Later, I add 7 to my set and remove 3, so the new sum is 14. I can verify this sum at any point by adding the numbers in my set (2+7+5) and comparing the result to 14.

However, I can also subtract a random number from the sum. If I subtract 6, I get 8. 8 is still a valid sum, but it's not the sum of *my set*. Likewise, when you "subtracted" `"Evil_banana"`, the result was a valid LtHash; but it's not a *useful* LtHash, because it doesn't correspond to your set. There is no way to throw an exception, because the LtHash itself does not know what elements you put in it, just like the number 14 doesn't know that it's the sum of 2, 7, and 5.

I recommend reading [this blog post](https://code.fb.com/security/homomorphic-hashing/) for an explanation of what LtHash is useful for. In my opinion, it is only likely to be useful in very specific circumstances. A Merkle tree or a standard hash is the correct choice for most applications.
